/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BuildingsRouteImport } from './routes/buildings'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as CustomerViewRouteImport } from './routes/customer-view'
import { Route as CustomersRouteImport } from './routes/customers'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as PaymentsRouteImport } from './routes/payments'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as StaffRouteImport } from './routes/staff'
import { Route as StaffViewRouteImport } from './routes/staff-view'
import { Route as CheckoutTokenRouteImport } from './routes/checkout.$token'
import { Route as InvoicesIdRouteImport } from './routes/invoices.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildingsRoute = BuildingsRouteImport.update({
  id: '/buildings',
  path: '/buildings',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerViewRoute = CustomerViewRouteImport.update({
  id: '/customer-view',
  path: '/customer-view',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersRoute = CustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentsRoute = PaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffRoute = StaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StaffViewRoute = StaffViewRouteImport.update({
  id: '/staff-view',
  path: '/staff-view',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutTokenRoute = CheckoutTokenRouteImport.update({
  id: '/checkout/$token',
  path: '/checkout/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIdRoute = InvoicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => InvoicesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/buildings': typeof BuildingsRoute
  '/collections': typeof CollectionsRoute
  '/companies': typeof CompaniesRoute
  '/customer-view': typeof CustomerViewRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-view': typeof StaffViewRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/invoices/$id': typeof InvoicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/buildings': typeof BuildingsRoute
  '/collections': typeof CollectionsRoute
  '/companies': typeof CompaniesRoute
  '/customer-view': typeof CustomerViewRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-view': typeof StaffViewRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/invoices/$id': typeof InvoicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/buildings': typeof BuildingsRoute
  '/collections': typeof CollectionsRoute
  '/companies': typeof CompaniesRoute
  '/customer-view': typeof CustomerViewRoute
  '/customers': typeof CustomersRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/jobs': typeof JobsRoute
  '/payments': typeof PaymentsRoute
  '/settings': typeof SettingsRoute
  '/staff': typeof StaffRoute
  '/staff-view': typeof StaffViewRoute
  '/checkout/$token': typeof CheckoutTokenRoute
  '/invoices/$id': typeof InvoicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/buildings'
    | '/collections'
    | '/companies'
    | '/customer-view'
    | '/customers'
    | '/invoices'
    | '/jobs'
    | '/payments'
    | '/settings'
    | '/staff'
    | '/staff-view'
    | '/checkout/$token'
    | '/invoices/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/buildings'
    | '/collections'
    | '/companies'
    | '/customer-view'
    | '/customers'
    | '/invoices'
    | '/jobs'
    | '/payments'
    | '/settings'
    | '/staff'
    | '/staff-view'
    | '/checkout/$token'
    | '/invoices/$id'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/buildings'
    | '/collections'
    | '/companies'
    | '/customer-view'
    | '/customers'
    | '/invoices'
    | '/jobs'
    | '/payments'
    | '/settings'
    | '/staff'
    | '/staff-view'
    | '/checkout/$token'
    | '/invoices/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BuildingsRoute: typeof BuildingsRoute
  CollectionsRoute: typeof CollectionsRoute
  CompaniesRoute: typeof CompaniesRoute
  CustomerViewRoute: typeof CustomerViewRoute
  CustomersRoute: typeof CustomersRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  JobsRoute: typeof JobsRoute
  PaymentsRoute: typeof PaymentsRoute
  SettingsRoute: typeof SettingsRoute
  StaffRoute: typeof StaffRoute
  StaffViewRoute: typeof StaffViewRoute
  CheckoutTokenRoute: typeof CheckoutTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buildings': {
      id: '/buildings'
      path: '/buildings'
      fullPath: '/buildings'
      preLoaderRoute: typeof BuildingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-view': {
      id: '/customer-view'
      path: '/customer-view'
      fullPath: '/customer-view'
      preLoaderRoute: typeof CustomerViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers': {
      id: '/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof CustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payments': {
      id: '/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof PaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staff-view': {
      id: '/staff-view'
      path: '/staff-view'
      fullPath: '/staff-view'
      preLoaderRoute: typeof StaffViewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$token': {
      id: '/checkout/$token'
      path: '/checkout/$token'
      fullPath: '/checkout/$token'
      preLoaderRoute: typeof CheckoutTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$id': {
      id: '/invoices/$id'
      path: '/$id'
      fullPath: '/invoices/$id'
      preLoaderRoute: typeof InvoicesIdRouteImport
      parentRoute: typeof InvoicesRoute
    }
  }
}

interface InvoicesRouteChildren {
  InvoicesIdRoute: typeof InvoicesIdRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesIdRoute: InvoicesIdRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BuildingsRoute: BuildingsRoute,
  CollectionsRoute: CollectionsRoute,
  CompaniesRoute: CompaniesRoute,
  CustomerViewRoute: CustomerViewRoute,
  CustomersRoute: CustomersRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  JobsRoute: JobsRoute,
  PaymentsRoute: PaymentsRoute,
  SettingsRoute: SettingsRoute,
  StaffRoute: StaffRoute,
  StaffViewRoute: StaffViewRoute,
  CheckoutTokenRoute: CheckoutTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}